### ISSUE TITLE
Metadata example not working

### ISSUE THREAD

**Issue by iamluciano** [spatialaudio/jackclient-python#69]
I get an error when running the metadata example, JACK-Client 0.5.0, Python 3.7.3, Ubuntu 19.04:

```
Traceback (most recent call last):
  File "metadata.py", line 12, in <module>
    client.set_property(client, jack.METADATA_PRETTY_NAME, 'Best Client Ever')
  File "/home/user/.local/lib/python3.7/site-packages/jack.py", line 1520, in set_property
    .format(key, subject))
ValueError: Unable to set property 'http://jackaudio.org/metadata/pretty-name' for subject 0

```

**Comment by mgeier** [comment]
I'm not sure, but this might only work in the latest version of JACK2.

If you are already using the latest JACK2, you could try JACK1 instead, which had metadata support earlier.

**Comment by iamluciano** [comment]
Thanks, I tried JACK1 0.125.0rc1 and works as expected:

```
Client "pretty" name: (b'Best Client Ever', '')
Port "pretty" name: (b'a good port', 'text/plain')
All client properties:
{'http://jackaudio.org/metadata/pretty-name': (b'Best Client Ever', '')}
All port properties:
{'http://jackaudio.org/metadata/pretty-name': (b'a good port', 'text/plain')}
All properties:
{4294967309: {'http://jackaudio.org/metadata/pretty-name': (b'a good port',
                                                            'text/plain')},
 8589934596: {'http://jackaudio.org/metadata/pretty-name': (b'Best Client Ever',
                                                            '')}}
```

For the record, metadata support is not compatible with latest JACK2 (1.9.12 by the time I wrote this).

**Comment by iamluciano** [comment]
I also confirm that metadata works when running JACK2 1.9.13, but fails for 1.9.12 (ie, the public binaries at http://jackaudio.org/downloads/). You were completely right, thanks.
